version: '2'
services:
  embulk:
    image: honto/embulk
    environment:
      PLUGINS: "embulk-input-mysql embulk-output-mysql"
      LOG_PATH: "--log /etc/embulk/log/embulk.log"
    volumes:
      - ./config:/etc/embulk
      - /var/lib/gems:/root/.embulk/jruby/
    links:
      - mysql
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./data:/var/lib/mysql
