in:
  type: mysql
  # driver_path: /etc/embulk/ojdbc7.jar
  host: mysql
  user: root
  password: "password"
  database: my_database1
  table: my_table
  select: "col1, col2, col3"
  where: "col4 != 'a'"
out:
  type: mysql
  host: mysql
  user: root
  password: "password"
  database: my_database2
  table: my_table
  mode: insert
